config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  devise_for :admins, :providers,
             skip: %i[sessions controllers]
  devise_scope :admin do
    get "/auth/google_oauth2/callback" => "admins/omniauth_callbacks#google_oauth2", as: :admin_google_oauth2_omniauth_callback
    get "/admins/sign_in" => "admins/sessions#new", as: :new_admin_session
  end

  devise_scope :provider do
    get "/providers/sign_in" => "providers/sessions#new", as: :new_provider_session
    post "/providers/sign_in" => "providers/sessions#create", as: :provider_session
    get "/providers/sign_out", to: "providers/sessions#destroy", as: :providers_logout

    # get callback only happens during tests - real IDP (SAML 2.0) only uses POST
    match "/providers/auth/saml/callback" => "providers/omniauth_callbacks#saml", via: %i[get post], as: :provider_saml_omniauth_callback
  end

  # dummy secured endpoint for testing
  resources :provider_secrets, only: [:index]

  root to: "start#index"

  resources :start, only: [:index]
  resources :status, only: [:index]

  resource :cookies, only: %i[show update]
  resource :privacy, as: :privacy, only: :show
  resource :accessibility, only: :show
  resource :help, only: :show
  resources :feature_flags, only: %i[index], path: "feature-flags"
  resources :updates, only: :index
  resources :basic_authentication_sessions, only: %i[new create]
  resources :documents, only: :show
  resources :feedbacks, only: %i[create update]

  get "/health", to: "status#health"
  get "/no-analytics", to: "cookies#no_analytics_mode"
  get "instant-:session_type", to: "instant_sessions#create", as: :instant_session
  get "robots.txt", to: "robots#index"
  get "/auth/subdomain_redirect", to: "oauth_redirects#subdomain_redirect", as: :subdomain_redirect
  post "/auth/google/redirect", to: "oauth_redirects#google_redirect", as: :google_oauth_redirect

  authenticate :admin, ->(admin) { admin.persisted? } do
    mount Blazer::Engine, at: "data"
  end

  # Catch and redirect old-format URLs
  get "estimates/:assessment_code/build_estimates/:step", to: "redirects#build_estimate"
  get "estimates/:assessment_code/check_answers/:step", to: "redirects#check"
  put "estimates/:assessment_code/build_estimates/:step", to: "redirects#build_estimate"
  put "estimates/:assessment_code/check_answers/:step", to: "redirects#check"
  get "estimates/:assessment_code/check_answers", to: "redirects#check_answers"
  get "estimates/:assessment_code", to: "redirects#result"
  get "estimates/:assessment_code/print", to: "redirects#result"
  get "estimates/:assessment_code/download", to: "redirects#result"
  get "estimates/:assessment_code/check_answers", to: "redirects#check_answers"
  get "estimates/:assessment_code/controlled_work_document_selections/new", to: "redirects#cw_forms"
  post "estimates/:assessment_code/controlled_work_document_selections", to: "redirects#cw_forms"
  get "download-cw-form/:assessment_code", to: "redirects#cw_forms"
  post "download-cw-form/:assessment_code", to: "redirects#cw_forms"
  get "which-controlled-work-form/:assessment_code", to: "redirects#cw_forms"
  post "which-controlled-work-form/:assessment_code", to: "redirects#cw_forms"
  get "provider_users", to: redirect("/new-check")
  get "do-you-give-legal-advice-or-provide-legal-services", to: redirect("/new-check")
  get "/print/:assessment_code", to: "results#download"

  get "new-check", to: "checks#new", as: :new_check
  get "check-answers/:assessment_code", to: "checks#check_answers", as: :check_answers
  get "service-end/:assessment_code", to: "checks#end_of_journey", as: :end_of_journey

  get "/download/:assessment_code", to: "results#download", as: :download_result
  get "/cw-form/:assessment_code", to: "controlled_work_document_selections#download", as: :download_cw_form

  get "select-cw-form/:assessment_code", to: "controlled_work_document_selections#new", as: :controlled_work_document_selection
  post "select-cw-form/:assessment_code", to: "controlled_work_document_selections#create"

  get "check-result/:assessment_code", to: "results#show", as: :result
  post "check-result/:assessment_code", to: "results#create"

  get ":step_url_fragment/:assessment_code", to: "forms#show", as: :step
  put ":step_url_fragment/:assessment_code", to: "forms#update"
  get ":step_url_fragment/:assessment_code/check", to: "change_answers#show", as: :check_step
  put ":step_url_fragment/:assessment_code/check", to: "change_answers#update"
end

app/views/estimate_flow/benefit_yesno.html.slim
- content_for :back
  = back_link(:assets, @estimate, @back_buttons_invoke_browser_back_behaviour)

.govuk-grid-column-two-thirds
  span.govuk-caption-l = t(".caption")

  = form_for(@form, url: wizard_path, method: :put) do |form|

    = form.govuk_error_summary t("generic.error_summary_title")

    = form.govuk_collection_radio_buttons :has_benefits, yes_no_options, :first, :last,
            legend: { text: t(".has_benefits.legend"), size: "xl", tag: "h1" },
            hint: { text: t(".has_benefits.hint") }

    = form.govuk_submit t("generic.save_and_continue")

= render "shared/sidebar_with_date", links: {}

app/views/estimate_flow/benefits_more.html.slim
- content_for :back
  = back_link(:assets, @estimate, @back_buttons_invoke_browser_back_behaviour)

.govuk-grid-column-two-thirds
  span.govuk-caption-l = t(".caption")
  h1.govuk-heading-l = t(".heading.text", count: @form.benefits.size)

  = govuk_table do |table|
    ruby:
      table.body do |body|
        @form.benefits.each_with_index do |item, index|
          body.row do |row|
            row.cell(text: item.fetch("benefit_type"))
            row.cell(text: item.fetch("benefit_amount"))
            row.cell(text: benefits_frequencies.fetch(item.fetch("benefit_frequency")))
            row.cell(text: link_to("Edit", estimate_build_estimate_path(@estimate_id, :edit_benefit, index:)))
            row.cell(text: button_to("Remove",
                  estimate_build_estimate_path(@estimate_id, :benefit_remove),
                  params: { index: }, method: "put"))
          end
        end
      end

  = form_for(@form, url: wizard_path, method: :put) do |form|

    = form.govuk_error_summary t("generic.error_summary_title")

    = form.govuk_collection_radio_buttons :more_benefits, yes_no_options, :first, :last,
            legend: { text: t(".more.legend"), size: "xl", tag: "h1" }

    = form.govuk_submit t("generic.save_and_continue")

= render "shared/sidebar_with_date", links: {}

app/views/estimate_flow/check_answers.html.slim
- content_for :back
  = back_link(:check_answers, @estimate, @back_buttons_invoke_browser_back_behaviour)

.govuk-grid-column-two-thirds
  h1.govuk-heading-xl
    = t(".heading")

  - @form.sections.each do |section|
    .govuk-grid-row  id="section-#{section.label}-header"
      .govuk-grid-column-two-thirds
        h2.govuk-heading-l id="#{section.label}-section"
          = t(".#{section.label}")
      .govuk-grid-column-one-third
        - if section.screen.present?
          p class="govuk-!-text-align-right"
            = link_to t("generic.change"),
                      estimate_check_answer_path(@estimate_id, section.screen),
                      class: "govuk-link govuk-!-font-size-19"

    - section.subsections.each do |subsection|
      - if subsection.label
        .govuk-grid-row id="subsection-#{subsection.label}-header"
          .govuk-grid-column-two-thirds
            h2.govuk-heading-m
              = t(".#{subsection.label}")
          .govuk-grid-column-one-third
            - if subsection.screen.present?
              p class="govuk-!-text-align-right"
                = link_to t("generic.change"),
                          estimate_check_answer_path(@estimate_id, subsection.screen),
                          class: "govuk-link govuk-!-font-size-19"

      dl class="govuk-summary-list govuk-!-margin-bottom-9" id="field-list-#{subsection.label || section.label}"
        - subsection.fields.each do |field|
          - case field.type
          - when "money"
            = render "money_check_answer",
                     label_text: t(".#{field.label}"),
                     value_text: field.value,
                     link: field.screen
          - when "boolean"
            = render "check_answer",
                     label_text: t(".#{field.label}"),
                     value_text: yes_no_boolean(field.value),
                     link: field.screen
          - when "number"
            = render "check_answer",
                     label_text: t(".#{field.label}"),
                     value_text: field.value || t("generic.not_applicable"),
                     link: field.screen
          - when "select"
            = render "check_answer",
                     label_text: t(".#{field.label}"),
                     value_text: t(".#{field.label}_options.#{field.value || 'not_provided'}"),
                     link: field.screen
          - when "money_with_frequency"
            - alt_value = field.alt_value if field.value&.to_f&.positive?
            = render "two_column_check_answer",
                     label_text: t(".#{field.label}"),
                     value_text: (field.value if field.value&.to_f&.positive?),
                     second_value_text: t(".#{field.label}_frequency_options.#{alt_value || 'not_applicable'}")
          - when "benefit"
            = render "money_check_answer",
                     label_text: field.label,
                     value_text: field.value,
                     path: (edit_estimate_check_benefits_answer_path(@estimate_id, field.alt_value, check_answers: true) if field.alt_value)
          - else
            - raise "Unknown field_type #{field.type}"

  h2.govuk-heading-m = t(".submission_instructions")
  p = t(".submission_explanation")

  = form_with(url: estimates_path) do |form|
    = hidden_field_tag :estimate_id, params[:estimate_id]

    = form.govuk_submit t(".call_to_action")

= render "shared/sidebar_with_date", links: {}

app/views/estimate_flow/edit_benefit.html.slim
- content_for :back
= link_to t("generic.back"), previous_wizard_path, class: "govuk-back-link"

.govuk-grid-column-two-thirds
  span.govuk-caption-l = t("estimate_flow.benefit_details.caption")
  h1.govuk-heading-l = t(".heading")

  = form_for(@form, url: wizard_path, method: :put) do |form|

    = form.govuk_error_summary t("generic.error_summary_title")

    = form.hidden_field :index

    = form.govuk_text_field :benefit_type,
            width: 20,
            label: { text: t("estimate_flow.benefit_details.type.label") }

    = render "shared/money_input",
            form:,
            field: :benefit_amount,
            width: 5,
            label_text: t("estimate_flow.benefit_details.amount.label")

    = form.govuk_collection_radio_buttons :benefit_frequency, benefits_options, :first, :last,
            legend: { text: t("estimate_flow.benefit_details.frequency.legend", size: "m") }

    = form.govuk_submit t("generic.save_and_continue")

= render "shared/sidebar_with_date", links: {}

app/views/estimate_flow/housing.html.slim
- content_for :page_title
  = t(".title")
- content_for :back do
  = back_link(:housing, @estimate, @back_buttons_invoke_browser_back_behaviour)

.govuk-grid-column-two-thirds
  = form_for(@form, url: wizard_path, method: :put) do |form|
    = form.govuk_error_summary t("generic.error_summary_title")
    = render "shared/heading",
             header_text: t(".title"),
             post_header_texts: [t(".hint_1"), t(".hint_2")]

    h2.govuk-heading-m class="govuk-!-margin-bottom-2"
      = t(".housing_payments")
    - t(".housing_payments_hints").each do |hint|
      span.govuk-caption-m class="govuk-!-margin-bottom-4"
        = hint
    = render "shared/money_input",
            form:,
            field: :housing_payments_value,
            width: 10,
            label_text: t(".enter_amount")
    = form.govuk_collection_radio_buttons :housing_payments_frequency,
                                          @form.frequencies(:housing_payments_frequency),
                                          :first,
                                          :last,
                                          legend: -> { tag.p(t(".select_frequency")) }

    = form.govuk_radio_buttons_fieldset :receives_housing_benefit,
                                        legend: { text: t(".receives_housing_benefit") },
                                        hint: lambda { \
                                            tag.p(t(".housing_benefit_hint_1"), class: "govuk-hint") + \
                                            tag.p(t(".housing_benefit_hint_2"), class: "govuk-hint") \
                                         } do
      = form.govuk_radio_button :receives_housing_benefit, true, label: { text: t("generic.yes_choice") }, link_errors: true do
        = render "shared/money_input",
                    form:,
                    field: :housing_benefit_value,
                    width: 5,
                    label_text: t(".enter_amount")
        = form.govuk_collection_radio_buttons :housing_benefit_frequency,
                                          @form.frequencies(:housing_benefit_frequency),
                                          :first,
                                          :last,
                                          legend: -> { tag.p(t(".how_often")) }
      = form.govuk_radio_button :receives_housing_benefit, false, label: { text: t("generic.no_choice") }

    = form.govuk_submit t("generic.save_and_continue")

= render "shared/question_sidebar",
        level_of_help: @estimate.level_of_help,
        links: outgoings_links(@estimate.level_of_help)

app/views/estimate_flow/housing_exit.html.slim
- content_for :page_title
  = t(".heading")
- content_for :back do
  = back_link(:housing_costs, @check, @back_buttons_invoke_browser_back_behaviour)
.govuk-grid-column-two-thirds
  = render "estimate_flow/forms/housing_exit", i18n_key: "housing_exit"

= render "shared/question_sidebar",
        level_of_help: @check.level_of_help,
         links: {}